[build-system]
requires = ["uv_build >= 0.9.26, <0.10.0"]
build-backend = "uv_build"

[project]
name = "flatten"
version = "0.0.1"
authors = [
  { name="Julien Perret", email="Julien.Perret@ign.fr" },
]
description = "A package to flatten geographical features"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "cvxpy>=1.8.1",
    "geojson>=3.2.0",
    "geopandas>=1.0.1",
    "neatnet>=0.1.5",
    "networkx>=3.2.1",
    "owslib>=0.31.0",
    "pyinterpolate>=1.2.1",
    "typer>=0.21.1",
]

[project.urls]
Homepage = "https://github.com/umrlastig/flatten/"
Issues = "https://github.com/umrlastig/flatten/issues"

[tool.uv.workspace]
members = [
    "flatten",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]

[project.scripts]
flatten_split = "flatten.split:app"
